const express = require('express');
const router = express.Router();

const nameMap = {
        'calculatorapp': 'calculator',
        'Notepad.exe': 'notepad',
        'wordpad.exe': 'wordpad',
        'mspaint.exe': 'paint',
        'explorer.exe': 'explorer',
        'chrome.exe': 'google chrome',
        'firefox.exe': 'mozilla firefox',
        'edge.exe': 'microsoft edge',
        'vlc.exe': 'vlc media player',
        'spotify.exe': 'spotify',
        'skype.exe': 'skype',
        'teams.exe': 'microsoft teams',
        'zoom.exe': 'zoom',
        'discord.exe': 'discord',
        'slack.exe': 'slack',
        'microsoftedge.exe': 'microsoft edge',
        'iexplore.exe': 'internet explorer',
        'opera.exe': 'opera',
        'safari.exe': 'safari',
        'git.exe': 'git',
        'gitbash.exe': 'git bash',
        'powershell.exe': 'powershell',
        'cmd.exe': 'command prompt',
        'terminal.exe': 'windows terminal',
        'taskmgr.exe': 'task manager',
        'taskmgr': 'task manager',
        'task manager': 'task manager',
        'VSCode.exe': 'visual studio code',
        'vscode.exe': 'visual studio code',
        'code.exe': 'visual studio code',
        'notepad++': 'notepad++',
        'zoomlauncher.exe': 'zoom',
        'zoom meeting.exe': 'zoom',
        'google chrome.exe': 'google chrome',
        'firefox.exe': 'mozilla firefox',
        'microsoft teams.exe': 'microsoft teams',
        'microsoft edge.exe': 'microsoft edge',
        'vlc media player.exe': 'vlc media player',
        'spotify.exe': 'spotify',
        'skype.exe': 'skype',
        'discord.exe': 'discord',
        'slack.exe': 'slack',
        'microsoft word.exe': 'microsoft word',
        'microsoft excel.exe': 'microsoft excel',
        'microsoft powerpoint.exe': 'microsoft powerpoint',
        'microsoft outlook.exe': 'microsoft outlook',
        'microsoft onenote.exe': 'microsoft onenote',
        'microsoft access.exe': 'microsoft access',
        'microsoft publisher.exe': 'microsoft publisher',
        'microsoft visio.exe': 'microsoft visio',
        'microsoft project.exe': 'microsoft project',
        'microsoft sharepoint.exe': 'microsoft sharepoint',
        'youtube.exe': 'youtube',
        'netflix.exe': 'netflix',
        'amazon prime video.exe': 'amazon prime video',
        'hulu.exe': 'hulu',
        'disney plus.exe': 'disney plus',
        'twitch.exe': 'twitch',
        'twitter.exe': 'twitter',
        'facebook.exe': 'facebook',
        'instagram.exe': 'instagram',
        'linkedin.exe': 'linkedin',
        'reddit.exe': 'reddit',
        'steam': 'steam',
        'canvas.exe': 'canvas',
        'bluestacks.exe': 'bluestacks',
        'telegram.exe': 'telegram',
        'whatsapp.exe': 'whatsapp',
        'signal.exe': 'signal',
        'microsoft edge webview2.exe': 'microsoft edge webview2',
        'gmail.exe': 'gmail',
        'webmail.exe': 'webmail',
        'microsoft store.exe': 'microsoft store',
        'chatgpt.exe': 'chatgpt',
        'internet explorer.exe': 'internet explorer',
        'steam.exe': 'steam',
        'msedgewebview2': 'Microsoft Edge',
        'msedge': 'Microsoft Edge',
        'chrome': 'Google Chrome',
        'firefox': 'Mozilla Firefox',
        'code': 'VS Code',
        'vscode': 'VS Code',
        'mongod': 'MongoDB',
        'node': 'Node.js',
        'powershell': 'PowerShell',
        'cmd': 'Command Prompt',
        'explorer': 'File Explorer',
        'notepad': 'Notepad',
        'wordpad': 'WordPad',
        'mspaint': 'Paint',
        'calc': 'Calculator',
        'olk': 'Microsoft Outlook',
        'msteams': 'Microsoft Teams',
       'ms-teamsupdate' : 'Microsoft Teams Update',
       
        // Add mappings for the processes you're seeing
        'lightshot': 'Lightshot Screenshot',
        'onenote': 'Microsoft OneNote',
        'teams': 'Microsoft Teams',
        'zoom': 'Zoom',
        'discord': 'Discord',
        'slack': 'Slack',
        'spotify': 'Spotify',
        'vlc': 'VLC Media Player',
        
        // HP-specific
        'hpcommrecovery': 'HP Recovery',
        'hpsystemeventutility': 'HP System Utility',
        'hpmedianetwork': 'HP Media Network',
        'omencommandcenter': 'OMEN Command Center',
        'Code.exe': 'Visual Studio Code',
        // Microsoft Office
        'winword': 'Microsoft Word',
        'msedge.exe': 'Microsoft Edge',
        'excel.exe': 'Microsoft Excel',
        'powerpoint.exe': 'Microsoft PowerPoint',
        'explorer.exe': 'File Explorer',
        'MongoDBCompass.exe': 'MongoDB Compass',
        'excel': 'Microsoft Excel',
        'powerpnt': 'Microsoft PowerPoint',
        'outlook': 'Microsoft Outlook',
        'msedgewebview2': 'Microsoft Edge',
        'teams': 'Microsoft Teams',
        'olk.exe': 'Microsoft Outlook',
        'youtube.com': 'YouTube',
        'CalculatorApp.exe': 'Calculator',
        'mail.google.com': 'Gmail',
        'outlook.office.com': 'Outlook Web',
        'web.whatsapp.com': 'WhatsApp Web',
        'linkedin': 'LinkedIn',
        'linkedinapp': 'LinkedIn',
        'telegram': 'Telegram',
        'instagram': 'Instagram',
        'iexplore': 'Internet Explorer',
        'msedge': 'Microsoft Edge',  // For YouTube/webmail in Edge
        'chrome': 'Google Chrome',   // For YouTube/webmail in Chrome
        'firefox': 'Firefox',        // For YouTube/webmail in Firefox
        'canva': 'Canva',
        'whatsapp': 'WhatsApp',
        'GitHubDesktop.exe': 'GitHub Desktop',
        'msteams.exe': 'Microsoft Teams',
        };

     router.get('/', (req, res) => {
    res.json(nameMap);
});

module.exports = router;